[build]
buildCommand = "SECRET_KEY_BASE_DUMMY=1 bundle exec rails assets:precompile"

[deploy]
preDeployCommand = "bin/rails db:prepare"
healthcheckPath = "/up"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
